name: Build credential files

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  VALIDATION_ENABLED: true

jobs:
  build_credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show workflow information
        run: |
            echo "Event: ${{ github.event_name }}"
            echo "Branch: ${{ github.ref_name }}"
            echo "Commit: ${{ github.sha }}"
            git log -1 --oneline
            git status --short

      - name: Validate credential definitions
        id: validation
        run: node .github/scripts/validate-credential-definitions.js
        continue-on-error: true
  

      - name: Show validation log
        if: always()
        run: |
         if [ -f .github/logs/script.log ]; then
          cat .github/logs/script.log
         else
            echo "Validation log was not found."
         fi

      - name: Generate credential types
        run: node .github/scripts/build-credential-types-list.js

      - name: Generate credentials data
        run: node .github/scripts/build-credential-data.js

      - name: Commit generated files
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      
          git add .github/logs/script.log
          git add .autogen/credential-types.json
          git add .autogen/credentials.json
      
          git commit -m "Auto update generated files [skip ci]" || echo "No changes"
          git push

      - name: Fail workflow if validation failed
        if: steps.validation.outcome == 'failure'
        run: |
         echo "Credential validation failed."
         exit 1
