name: Build credentials data

on:
  push:
    paths:
      - "**/translations/en.json"
      - "credential-types-list.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run script
        run: node scripts/build-credential-data.js

      - name: Commit generated credentials-data file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add credentials-data.json
          git commit -m "Auto update credentials data" || echo "No changes"
          git push